apiVersion: apps/v1
kind: Deployment
metadata:
    name: client-deployment
spec:
    # number of identical pods to be created
    replicas: 1
    selector:
        matchLabels:
            component: web
    template:
        metadata:
            labels:
                component: web
        spec:
            containers:
                - name: client
                  image: domicch/multi_docker_k8s_client
                  ports:
                    - containerPort: 3000
                  # Need this flag to prevent container terminate immediately in k8s environment (like docker-compose case). 
                  # Should be problem of create-react app
                  stdin: true
