apiVersion: apps/v1
kind: Deployment
metadata:
    name: server-deployment
spec:
    # number of identical pods to be created
    replicas: 1
    selector:
        matchLabels:
            component: server
    template:
        metadata:
            labels:
                component: server
        spec:
            containers:
                - name: server
                  image: domicch/multi_docker_k8s_server
                  ports:
                    - containerPort: 5000
                  env:
                    - name: REDIS_HOST
                      value: redis-cluster-ip-service
                    - name: REDIS_PORT
                      value: "6379"
                    - name: PGUSER
                      value: postgres
                    - name: PGHOST
                      value: postgres-cluster-ip-service
                    - name: PGPORT
                      value: "5432"
                    - name: PGDATABASE
                      value: postgres
                    - name: PGPASSWORD
                      valueFrom:
                        secretKeyRef:
                          name: pgpassword
                          key: PGPASSWORD